services:
  app:
    image: todo-front-dev
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    build:
      context: . 
      dockerfile: dev.Dockerfile
    container_name: todo-front-dev-proxied