services:
  app:
    image: hello-front-dev
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    build:
      context: . 
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    container_name: hello-front-dev-proxied