services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes'] 
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mypassword
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment: 
      - REDIS_URL=redis://@redis:6379/0
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./:/usr/src/app
    
    